name: Validate Changes on Push

on:
  push:
    branches:
      - main  # Change this to your desired branch

    paths: 
      - 'force-app/**'

jobs:
  BUILD:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Verify Salesforce CLI installation
        run: sf --version

      - name: Autorize ORG
        run: |
          'echo "${{ secrets.SALESFORCE_AUTH_URL }}" > authFile.json'
          'echo cat ./authFile.json'
          'echo sf org login sfdx-url -f authFile.json -s'

      - name: Run Test
        run: sf apex run test -l RunSpecifiedTests -n CustomFileUploadCtrlTest -r human -y -c -d ./

      - name: Upload code coverage for Apex to Codecov.io
        uses: codecov/codecov-action@v2
        with:
          flags: Apex
        env:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
